name-template: 'v$NEXT_PATCH_VERSION ğŸŒˆ'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH.$THIRD'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    labels: 
      - ''  
template: |
  ## Whatâ€™s Changed

  $CHANGES