version-template: 'v$MAJOR.$MINOR.$PATCH-v$CPV'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    labels: 
      - ''  
template: |
  ## Whatâ€™s Changed

  $CHANGES